### ISSUE TITLE
Package installation failed

### ISSUE THREAD

**Issue by KatrienQ** [kodaim1115/CYBERTRACK#1]
I'm working in R version 3.6.1 and I get an error while installing the package.  
devtools::install_github("kodaim1115/CYBERTRACK") 
In the "installing *source* package ‘CYBERTRACK’ ..." I get this error:  
  
```
Error: package or namespace load failed for ‘CYBERTRACK’ in dyn.load(file, DLLpath = DLLpath, ...):  
   unable to load shared object '/private/var/folders/_5/j148dbqs45vbnkzydqgjs0zr0000gp/T/Rtmpxj5m6C/Rinst23de797ed8d7/00LOCK-CYBERTRACK/00new/CYBERTRACK/libs/CYBERTRACK.so':  
      dlopen(/private/var/folders/_5/j148dbqs45vbnkzydqgjs0zr0000gp/T/Rtmpxj5m6C/Rinst23de797ed8d7/00LOCK-CYBERTRACK/00new/CYBERTRACK/libs/CYBERTRACK.so, 6): Symbol not found: __Z10cybertrackRKN4arma3MatIdEERKiS1_NS_3RowIdEES3_RKNS_4CubeIdEERKdSD_S3_S5_iS7_
      Referenced from: /private/var/folders/_5/j148dbqs45vbnkzydqgjs0zr0000gp/T/Rtmpxj5m6C/Rinst23de797ed8d7/00LOCK-CYBERTRACK/00new/CYBERTRACK/libs/CYBERTRACK.so. 
      Expected in: flat namespace
    in /private/var/folders/_5/j148dbqs45vbnkzydqgjs0zr0000gp/T/Rtmpxj5m6C/Rinst23de797ed8d7/00LOCK-CYBERTRACK/00new/CYBERTRACK/libs/CYBERTRACK.so
```

**Comment by nicfew** [comment]
I have a similar problem!! Any solution ???


  Error: package or namespace load failed for ‘CYBERTRACK’ in dyn.load(file, DLLpath = DLLpath, ...):
    unable to load shared object '/private/var/folders/lp/853dqcjj2mzfsf96h7qcvv3m0000gp/T/RtmpPrZCN8/Rinst6539503b20c6/00LOCK-CYBERTRACK/00new/CYBERTRACK/libs/CYBERTRACK.so':
     dlopen(/private/var/folders/lp/853dqcjj2mzfsf96h7qcvv3m0000gp/T/RtmpPrZCN8/Rinst6539503b20c6/00LOCK-CYBERTRACK/00new/CYBERTRACK/libs/CYBERTRACK.so, 6): Symbol not found: __Z10cybertrackRKN4arma3MatIdEERKiS1_NS_3RowIdEES3_RKNS_4CubeIdEERKdSD_S3_S5_iS7_
     Referenced from: /private/var/folders/lp/853dqcjj2mzfsf96h7qcvv3m0000gp/T/RtmpPrZCN8/Rinst6539503b20c6/00LOCK-CYBERTRACK/00new/CYBERTRACK/libs/CYBERTRACK.so
     Expected in: flat namespace
    in /private/var/folders/lp/853dqcjj2mzfsf96h7qcvv3m0000gp/T/RtmpPrZCN8/Rinst6539503b20c6/00LOCK-CYBERTRACK/00new/CYBERTRACK/libs/CYBERTRACK.so
   Error: loading failed
   Execution halted
   ERROR: loading failed




Cheers

**Comment by kodaim1115** [comment]
Thanks for pointing it out. 
I fixed bugs so the problem should be solved now.
